// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlwx2PNyqA_lXOq7R4t5_xbWTghtIS8IQ',
    appId: '1:804871130995:android:432789e0c4b3eb14db3f06',
    messagingSenderId: '804871130995',
    projectId: 'todo-provider-2k24-barba',
    storageBucket: 'todo-provider-2k24-barba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_oVhhgWSkQgRqAdj91xNTv36dRzaMDcI',
    appId: '1:804871130995:ios:a651c30dd526e24adb3f06',
    messagingSenderId: '804871130995',
    projectId: 'todo-provider-2k24-barba',
    storageBucket: 'todo-provider-2k24-barba.firebasestorage.app',
    androidClientId: '804871130995-3h8uh3ckhqgb384u5urp2u9qr9qj10cr.apps.googleusercontent.com',
    iosClientId: '804871130995-rnig9t7080sindnst17p96i9ejmfi3v5.apps.googleusercontent.com',
    iosBundleId: 'com.barbatech.newTodoList',
  );

}